### ISSUE TITLE
Convert NextJS pages to TypeScript

### ISSUE THREAD

**Issue by mattfredericksen** [ModularHistory/modularhistory#251]
https://nextjs.org/docs/basic-features/typescript

https://material-ui.com/guides/typescript/#usage-of-component-prop

https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter

https://react-typescript-cheatsheet.netlify.app//docs/basic/setup

**Comment by iacobfred** [comment]
Moved this to Jira.
